#!/usr/bin/env node

const books = [
  "The 7 Habits of Highly Effective People",
  "Fumbling the Future",
  "How to Listen with Intention",
  "Nonviolent Communication",
  "Wywieranie wpływu na ludzi",
  "Start with Why",
  "Never Split the Difference",
  "What Got You Here Won't Get You There",
  "Erystyka",
  "Lost Art of Listening",
  "Managing Up",
  "The Culture Map",
  "Negocjacje z potworami",
  "Tiny Habits",
  "Atomic Habits",
  "Deep Work",
  "Getting Things Done",
  "How to Listen",
  "The Signal and the Noise",
  "The One Thing",
  "Leaders Eat Last",
  "Crucial Conversations",
  "The Decision Book",
  "How to Win Friends and Influence People",
  "Scrum",
  "Nic do ukrycia",
  "Mindshift",
  "Finish",
  "Jak czytać ludzi",
  "The Productivity Project",
  "Eat That Frog!",
  "Learn Like a Pro",
  "Find Your Why",
  "The Cynefin Mini-Book",
  "Inteligencja emocjonalna",
  "Read People Like a Book",
  "Sztuka negocjacji",
  "Pułapki myślenia",
  "The Software Developer's Career Handbook",
  "Software Engineering at Google",
  "The Art of Agile Development",
  "Full Statck Testing",
  "Learning Chaos Engineering",
  "Chaos Engineering",
  "Practical Statistics for Data Scientists",
  "Fluent Python",
  "iOS 15 Programming Fundamentals with Swift",
  "Bash Idioms",
  "Effective Rust",
  "Learning Java",
  "Java Cookbook",
  "Java Performance",
  "C# 12 in a Nutshell",
  "Learning Perl",
  "JavaScript: The Definitive Guide",
  "Programming TypeScript",
  "Effective TypeScript",
  "Learning Go",
  "Tidy First?",
  "Database Internals",
  "Kafka: The Definitive Guide",
  "Fundamentals of DevOps and Software Delivery",
  "Kubernetes: Up & Running",
  "Production Kubernetes",
  "Kubernetes Patterns",
  "Networking and Kubernetes",
  "Hacking Kubernetes",
  "Learning Helm",
  "Learning OpenTelemetry",
  "Cloud Application Architecture Patterns",
  "Cloud Native Transformation",
  "Building Event-Driven Microservices",
  "Monolith to Microservices",
  "Building Microservices",
  "Data Engineering design Patterns",
  "Learning Domain-Drivern Design",
  "Graph Algorithms",
  "Fundamentals of Software Architecture",
  "Software Architecture: The Hard Parts",
  "Building Evolutionary Architectures",
  "Designing Data-Intensive Applications",
  "BGP",
  "Optimizing Java",
  "Mikrousługi",
  "Learning the Bash Shell",
  "Introducing Erlang",
  "SQL Tuning",
  "The Software Architect Elevator",
  "Eloquent JavaScript",
  "Python Crash Course",
  "PHP Crash Course",
  "Effective C",
  "C++ Crash Course",
  "The Rust Programming Language",
  "Rust for Rustaceans",
  "Racket Programming the Fun Way",
  "Kotlin from Scratch",
  "Designing Electronics that Work",
  "Getting Started with FPGAS",
  "Computer Architecture, from the Stone Age to the Quantum Age",
  "Understanding the Machine",
  "Thinking Low Level, Writing High Level",
  "Engineering Software",
  "The Art of 64-Bit Assembly",
  "The Art of ARM Assembly",
  "Writing a C Compiler",
  "Algorithmic Thinking",
  "Dive into Algorithms",
  "Graph Algorithms the Fun Way",
  "Data Structures the Fun Way",
  "Quantum Computing",
  "DevOps for the Desperate",
  "Effective Shell",
  "Wicked Cool Shell Scripts",
  "How Linux Works",
  "Linux Basics for Hackers",
  "Hacking APIs",
  "The Ghidra Book",
  "Computer Graphics from Scratch",
  "Learn Physics with Functional Programming",
  "Bayesian Statistics the Fun Way",
  "Math for Programming",
  "Math for Security",
  "Metasploit",
  "Red Team Engineering",
  "Evasive Malware",
  "Serious Cryptography",
  "Penetration Testing",
  "From Day Zero to Zero Day",
  "Bug Bounty Bootcamp",
  "Ethical Hacking",
  "Evading EDR",
  "Black Hat Bash",
  "Black Hat GraphQ",
  "Cyberjutsu",
  "The Hardware Hacking Handbook",
  "Attacking Network Protocols",
  "Practical Binary Analysis",
  "Practical Social Engineering",
  "Black Hat Python",
  "Black Hat Go",
  "Microcontroller Exploits",
  "PoC || GTFO Vol. 1",
  "PoC || GTFO Vol. 2",
  "PoC || GTFO Vol. 3",
  "Hasks, Leaks, and Revelations",
  "Hacking: the Art of Explotation",
  "Open Circuits",
  "Realm of Racket",
  "The Missing Readme",
  "Learn You a Haskell for Great Good!",
  "Game Boy Coding Adventure",
  "Clojure for the Brave and True",
  "The Art Of Computer Programming Vol. 1",
  "The Art Of Computer Programming Vol. 2",
  "The Art Of Computer Programming Vol. 3",
  "The Art Of Computer Programming Vol. 4A",
  "The Art Of Computer Programming Vol. 4B",
  "The Art Of Computer Programming Vol. 4 Fascile 7",
  "Effective C++",
  "More Effective C++",
  "The Go Programming Language",
  "Advanced Programming in the UNIX Environment",
  "TCP/IP Illustrated, Volume 1",
  "TCP/IP Illustrated, Volume 2",
  "TCP/IP Illustrated, Volume 3",
  "Design Patterns",
  "UML Distilled",
  "Using UML",
  "Real-Time Design Patterns",
  "Analysis Patterns",
  "Refactoring, First Edition",
  "NoSQL Distilled",
  "Writing Effective Use Cases",
  "Extreme Programming Explained",
  "The Mythical Man-Month",
  "Domain Drivern Design",
  "Hacker's Delight",
  "The C++ Programming Language",
  "Domain-Driven Design Distilled",
  "Implementing Domain-Driven Design",
  "The D Programming Language",
  "Agile Testing",
  "More Agile Testing",
  "Succeeding with Agile",
  "Essential Scrum",
  "Agile Product Management with Scrum",
  "Implementation Patterns",
  "Test-Driven Development",
  "Continuous Integration",
  "Continuous Delivery",
  "Domain-Specific Languages",
  "Refactoring to Patterns",
  "Enterprise Integration Patterns",
  "Patterns of Enterprise Application Architecture",
  "Refactoring, Second Edition",
  "Patterns of Distributed Systems",
  "Strategic Monoliths and Microservices",
  "Computer Systems",
  "Digital Design",
  "Compilers",
  "The Pragmatic Programmer",
  "Core Java: Volume I",
  "Core Java: Volume II",
  "Effective Python",
  "Swift for the Really Impatient",
  "Core Java for the Impatient",
  "Scala for the Impatient",
  "Modern Operating Systems",
  "Effective Java",
  "Software Architecture and Decision-Making",
  "Clean Code",
  "Clean Architecture",
  "Clean Craftmanship",
  "Clean Coder",
  "Programming Principles and Practice Using C++",
  "UNIX and Linux ystem Administration Handbook",
  "C++ for the Impatient",
  "A Tour of C++",
  "Erlang and OTP in Action",
  "Haskell in Depth",
  "Functional Programming in Scala",
  "Functional Programming in C#",
  "MongoDB 8.0 in Action",
  "Acing the System Design Interview",
  "Just Use Postgres!",
  "C# in Depth",
  "Generative Art",
  "Modern Angular",
  "Dart in Action",
  "Amazon Web Services in Action",
  "Microservices Patterns",
  "Street Coder",
  "100 Java Mistakes",
  "Kafka Streams in Action",
  "Kubernetes for Developers",
  "The Joy of JavaScript",
  "Troubleshooting Java",
  "Redis in Action",
  "Kotlin in Action",
  "PostgreSQL Mistakes",
  "Rust in Action",
  "Idiomatic Rust",
  "Flutter in Action",
  "Geometry for Programmers",
  "The Well-Grounded Rubyist",
  "RxJS in Action",
  "100 Go Mistakes",
  "Elixir in Action",
  "Modern C",
  "The Well-Grounded Python Developer",
  "Unit Testing Principles, Practices, and Patterns",
  "Java Persistence",
  "The Well-Grounded Java Developer",
  "Spring in Action",
  "Advanced Algorithms and Data Structures",
  "Cloud Native Spring in Action",
  "Spring Microservices in Action",
  "Functional Design and Architecture",
  "React in Depth",
  "Deep Learning with PyTorch",
  "Dependency Injection",
  "Swift in Depth",
  "Spring Boot in Practice",
  "Spring Start Here",
  "Grokking Algorithms",
  "Grokking Data Structures",
  "Grokking Simpliciy",
  "Grokking Functional Programming",
  "Grokking Streaming Systems",
  "Grokking Deep Learning",
  "Grokking Concurrency",
  "Grokking Web Application Security",
  "Grokking Continuous Delivery",
  "Design It!",
  "Release It!",
  "Programming Ruby 3.3",
  "Agile Web Development with Rails 8",
  "Domain Modeling Made Functional",
  "Effective Haskell",
  "Programming Erlang",
  "The Art of Elixir",
  "Understanding Distributed System",
  "Secret Colors",
  "Mastering Behavioral Interviews",
  "Staff Engineer",
  "Smalltalk Best Practice Patterns",
  "The C Programming Language",
  "Working Effectively with Legacy Code",
  "Introduction to Algorithms",
  "Structure and Interpretation of Computer Programs",
  "Software Design Decoded",
  "Deep Learning",
  "The Joy of Cryptography",
  "Critical Thinking",
  "The Internet Stack",
  "Game Programming Patterns",
  "Crafiting Interpreters",
  "A Philosophy of Software Design",
  "Debugging",
  "Cloud Strategy",
  "Platform Strategy",
  "Computer Architecture, a Quantitative Approach",
  "Real World OCaml",
  "Programming in Lua",
  "Distributed Systems",
  "System Design Interview, volume 2",
  "Expert Delphi",
  "The Software Engineer's Guidebook",
  "Silbershatz's Operating System Concepts",
  "Algorithms to Live by",
  "Język ANSI C",
  "Język ANSI C, ćwiczenia i rozwiązania",
  "Język C++",
  "Język C++, ćwiczenia i rozwiązania",
  "Model obiektu w C++",
  "Programowanie w środowisku system UNIX",
  "Programowanie w systemie UNIX",
  "Wprowadzenie do algorytów",
  "Sztuka programowania tom 1, zeszyt 1",
  "Sztuka programowania tom 1",
  "Sztuka programowania tom 2",
  "Sztuka programowania tom 3",
  "Sztuka programowania tom 4, zeszyt 1",
  "Sztuka programowania tom 4, zeszyt 2",
  "Struktura i interpretacja programów komputerowych",
  "Rzecz o istocie informatyki",
  "Algorytmy aproksymacyjne",
  "Algorytmy genetyczne i ich zastosowania",
  "Algorytmy + struktury danych = programy",
  "Kombinatoryka dla programistów",
  "Logika matematyczna w informatyce",
  "Elementy grafiki komputerowej",
  "Złożoność obliczeniowa",
  "Podstawy oprogramowania",
  "Perełki oprogramowania",
  "Więcej perełek oprogramowania",
  "Podstawy programowania współbieżnego i rozproszonego",
  "Systemy rozproszone",
  "Kompilatory, Klasyka Informatyki",
  "Wprowadzenie do systemów baz danych",
  "Podstawowy wykład z systemów baz danych",
  "System baz danych",
  "Implementacja systemów baz danych",
  "Inżynieria oprogramowania",
  "TEX. Przewodnik użytkownika",
  "Podstawy systemów operacyjnych, tom 1",
  "Podstawy systemów operacyjnych, tom 2",
  "Algorytmy i struktury danych",
  "Jak to rozwiązać, czyli nowoczesna heurystyka",
  "Kompilatory, PWN",
  "Wprowadzenie do grafiki komputerowej",
  "Matematyka dyskretna",
  "Matematyka konkretna",
  "Exploration in Monte Carlo Methods",
  "Linear Algebra Done Right",
  "Understanding Analysis",
  "Beginning in Algebraic Geometry",
  "Geometric Methods and Applications",
  "Geometry, Audin",
  "Guide to Teaching Puzzle-based Learning",
  "Guide to Competitive Programming",
  "Cryptography Made Simple",
  "Understanding Cryptography",
  "The Algorithm Design Manual",
  "Tablice Matematyczne",
  "Geometry, Brannan, Esplen, Gray",
  "Winning Ways for Your Mathematical Plays vol. 1",
  "Winning Ways for Your Mathematical Plays vol. 2",
  "Winning Ways for Your Mathematical Plays vol. 3",
  "Winning Ways for Your Mathematical Plays vol. 4",
  "Codebreaking, a Practical Guide",
  "The Book of Why",
  "The Art of Statistics",
  "The History of Graphic Design vol. 1",
  "The History of Graphic Design vol. 2",
  "Logo Modernism",
  "You're Invited",
  "Making and Breaking the Grid",
  "Sans in Use",
  "Serif in Use",
  "Stencil in Use",
  "Display in Use",
  "A Book on Books",
  "Jak dobrze pisać",
  "Graphic Design Rules",
  "The Designer's Dictionary of Color",
  "Człowiek i jego znaki",
  "Writing Tools",
  "How to Write Short",
  "The Creative Act",
  "Murder Your Darlings",
  "Kreatywność",
  "Posuta Poster",
  "Don't Make Me Think!",
  "Making Comics",
  "Understanding Comics",
  "Help! for Writers",
  "Zen in the Art of Archery",
  "Steal like an Artist",
  "Show Your Work!",
  "How to (Use Graphic Design)",
  "Sieci Petriego",
  "Rational Unified Process od strony praktycznej",
  "Rational Unified Process od strony teoretycznej",
  "Jak pisać efektywne przypadki użycia",
  "Stosowanie przypadków użycia",
  "Zarządzanei wymaganiami",
  "Tworzenie architektury oprogramowania",
  "Architekture oprogramowania w praktyce",
  "Oprogramowanie komponentowe",
  "Wzorce projektowe",
  "Komponenty w UML",
  "OCL precyzyjne modelowanie w UML",
  "Metody obiektowe",
  "Nowoczesne projektowanie w C++",
  "Testowanie systemów obiektowych",
  "Refaktoryzacja",
  "Lekcja programowania",
  "Pragmatyczny programista",
  "Jak kierować zespołem programistów",
  "Zarządzanie procesem tworzenia systemów informacyjnych",
  "Zarządzanie architekturocentrycznym procesem tworzenia oprogramowania",
  "Asortyment produktów programowych",
  "Metodyka wprowadzania oprogramowania na rynek",
  "Podstawy techniczne inzynierii oprogramowania",
  "Praktyczne podejście do inżynierii oprogramowania",
]

const rand = (array) => {
  const i = Math.floor(Math.random() * array.length);
  return array[i];
};

console.log(rand(books))
