#!/usr/bin/env node

const books = [
  "The 7 Habits of Highly Effective People",
  "How to Listen with Intention",
  "Nonviolent Communication",
  "Wywieranie wpływu na ludzi",
  "Never Split the Difference",
  "Erystyka",
  "Lost Art of Listening",
  "Jak dobrze pisać",
  "Managing Up",
  "Tiny Habits",
  "Writing Tools",
  "Negocjacje z potworami",
  "Atomic Habits",
  "Deep Work",
  "Getting Things Done",
  "Człowiek i jego znaki",
  "How to Listen",
  "The Signal and the Noise",
  "The One Thing",
  "The Book of Why",
  "Crucial Conversations",
  "The Decision Book",
  "Scrum",
  "Nic do ukrycia",
  "Mindshift",
  "Finish",
  "Jak czytać ludzi",
  "The Productivity Project",
  "Eat That Frog!",
  "Learn Like a Pro",
  "The Cynefin Mini-Book",
  "Inteligencja emocjonalna",
  "Making and Breaking the Grid",
  "The Art of Statistics",
  "Sztuka negocjacji",
  "Don't Make Me Think!",
  "Help! for Writers",
  "Pułapki myślenia",
  "The Software Developer's Career Handbook",
  "Software Engineering at Google",
  "The Art of Agile Development",
  "Full Statck Testing",
  "Learning Chaos Engineering",
  "Chaos Engineering",
  "Fluent Python",
  "iOS 15 Programming Fundamentals with Swift",
  "Bash Idioms",
  "Effective Rust",
  "Learning Java",
  "Java Cookbook",
  "Java Performance",
  "C# 12 in a Nutshell",
  "JavaScript: The Definitive Guide",
  "Programming TypeScript",
  "Effective TypeScript",
  "Learning Go",
  "Tidy First?",
  "Database Internals",
  "Kafka: The Definitive Guide",
  "Fundamentals of DevOps and Software Delivery",
  "Kubernetes: Up & Running",
  "Production Kubernetes",
  "Kubernetes Patterns",
  "Networking and Kubernetes",
  "Hacking Kbernetes",
  "Learning Helm",
  "Learning OpenTelemetry",
  "Building Event-Driven Microservices",
  "Cloud Application Architecture Patterns",
  "Cloud Native Transformation",
  "Monolith to Microservices",
  "Building Microservices",
  "Data Engineering design Patterns",
  "Learning Domain-Drivern Design",
  "Graph Algorithms",
  "Fundamentals of Software Architecture",
  "Software Architecture: The Hard Parts",
  "Building Evolutionary Architectures",
  "Learning the Bash Shell",
  "Mikrousługi",
  "SQL Tuning",
  "Designing Data-Intensive Applications",
  "The Software Architect Elevator",
  "Eloquent JavaScript",
  "Python Crash Course",
  "PHP Crash Course",
  "Effective C",
  "C++ Crash Course",
  "The Rust Programming Language",
  "Rust for Rustaceans",
  "Racket Programming the Fun Way",
  "Kotlin from Scratch",
  "Getting Started with FPGAS",
  "The Art of 64-Bit Assembly",
  "The Art of ARM Assembly",
  "Writing a C Compiler",
  "Algorithmic Thinking",
  "Dive into Algorithms",
  "Graph Algorithms the Fun Way",
  "Data Structures the Fun Way",
  "Quantum Computing",
  "DevOps for the Desperate",
  "Effective Shell",
  "Wicked Cool Shell Scripts",
  "How Linux Works",
  "Linux Basics for Hackers",
  "Hacking APIs",
  "The Ghidra Book",
  "Math for Programming",
  "Bayesian Statistics the Fun Way",
  "Math for Security",
  "Serious Cryptography",
  "From Day Zero to Zero Day",
  "Bug Bounty Bootcamp",
  "Black Hat Bash",
  "Attacking Network Protocols",
  "Hasks, Leaks, and Revelations",
  "Erlang and OTP in Action",
  "Haskell in Depth",
  "Functional Programming in Scala",
  "Functional Programming in C#",
  "MongoDB 8.0 in Action",
  "Acing the System Design Interview",
  "Just Use Postgres!",
  "C# in Depth",
  "Modern Angular",
  "Dart in Action",
  "Amazon Web Services in Action",
  "Microservices Patterns",
  "100 Java Mistakes",
  "Kafka Streams in Action",
  "Kubernetes for Developers",
  "The Joy of JavaScript",
  "Troubleshooting Java",
  "Redis in Action",
  "Kotlin in Action",
  "PostgreSQL Mistakes",
  "Rust in Action",
  "Idiomatic Rust",
  "Flutter in Action",
  "Geometry for Programmers",
  "The Well-Grounded Rubyist",
  "RxJS in Action",
  "100 Go Mistakes",
  "Elixir in Action",
  "Modern C",
  "The Well-Grounded Python Developer",
  "Unit Testing Principles, Practices, and Patterns",
  "Java Persistence",
  "The Well-Grounded Java Developer",
  "Spring in Action",
  "Advanced Algorithms and Data Structures",
  "Cloud Native Spring in Action",
  "Spring Microservices in Action",
  "Functional Design and Architecture",
  "React in Depth",
  "Deep Learning with PyTorch",
  "Dependency Injection",
  "Swift in Depth",
  "Spring Boot in Practice",
  "Generative Art",
  "Spring Start Here",
  "Grokking Algorithms",
  "Grokking Data Structures",
  "Grokking Simpliciy",
  "Grokking Functional Programming",
  "Grokking Streaming Systems",
  "Grokking Deep Learning",
  "Grokking Concurrency",
  "Grokking Web Application Security",
  "Grokking Continuous Delivery",
  "The Art Of Computer Programming Vol. 1",
  "The Art Of Computer Programming Vol. 2",
  "The Art Of Computer Programming Vol. 3",
  "The Art Of Computer Programming Vol. 4A",
  "The Art Of Computer Programming Vol. 4B",
  "The Art Of Computer Programming Vol. 4 Fascile 7",
  "The C++ Programming Language",
  "Effective C++",
  "More Effective C++",
  "The Go Programming Language",
  "Advanced Programming in the UNIX Environment",
  "TCP/IP Illustrated, Volume 1",
  "TCP/IP Illustrated, Volume 2",
  "TCP/IP Illustrated, Volume 3",
  "Design Patterns",
  "UML Distilled",
  "Real-Time Design Patterns",
  "Refactoring, First Edition",
  "Analysis Patterns",
  "NoSQL Distilled",
  "Writing Effective Use Cases",
  "Extreme Programming Explained",
  "The Mythical Man-Month",
  "Domain Drivern Design",
  "Domain-Driven Design Distilled",
  "Implementing Domain-Driven Design",
  "Agile Testing",
  "More Agile Testing",
  "Succeeding with Agile",
  "Essential Scrum",
  "Agile Product Management with Scrum",
  "Implementation Patterns",
  "Continuous Integration",
  "Continuous Delivery",
  "Domain-Specific Languages",
  "Refactoring to Patterns",
  "Enterprise Integration Patterns",
  "Patterns of Enterprise Application Architecture",
  "Refactoring, Second Edition",
  "Patterns of Distributed Systems",
  "Strategic Monoliths and Microservices",
  "Compilers",
  "The Pragmatic Programmer",
  "Scala for the Impatient",
  "Core Java for the Impatient",
  "Effective Java",
  "Software Architecture and Decision-Making",
  "The C Programming Language",
  "Programming Principles and Practice Using C++",
  "A Tour of C++",
  "UNIX and Linux ystem Administration Handbook",
  "Structure and Interpretation of Computer Programs",
  "Introduction to Algorithms",
  "Programming Ruby 3.3",
  "Effective Haskell",
  "The Art of Elixir",
  "Uderstanding Distributed System",
  "Jastering Behavioral Interviews",
  "Staff Engineer",
  "Working Effectively with Legacy Code",
  "Crafiting Interpreters",
  "Game Programming Patterns",
  "Silbershatz's Operating System Concepts",
  "Distributed Systems",
  "System Design Interview, volume 2",
  "Microcontroller Exploits",
  "Cloud Strategy",
  "Platform Strategy",
  "Core Java: Volume I",
  "Debugging",
  "Sieci Petriego",
  "Rational Unified Process od strony praktycznej",
  "Rational Unified Process od strony teoretycznej",
  "Jak pisać efektywne przypadki użycia",
  "Stosowanie przypadków użycia",
  "Zarządzanei wymaganiami",
  "Tworzenie architektury oprogramowania",
  "Architekture oprogramowania w praktyce",
  "Oprogramowanie komponentowe",
  "Wzorce projektowe",
  "Komponenty w UML",
  "OCL precyzyjne modelowanie w UML",
  "Metody obiektowe",
  "Nowoczesne projektowanie w C++",
  "Testowanie systemów obiektowych",
  "Refaktoryzacja",
  "Lekcja programowania",
  "Pragmatyczny programista",
  "Jak kierować zespołem programistów",
  "Zarządzanie procesem tworzenia systemów informacyjnych",
  "Zarządzanie architekturocentrycznym procesem tworzenia oprogramowania",
  "Asortymet produktów programowych",
  "Metodyka wprowadzania oprogramowania na rynek",
  "Podstawy techniczne inzynierii oprogramowania",
  "Praktyczne podejście do inzynierii oprogramowania",
  "Język ANSI C",
  "Język ANSI C, ćwiczenia i rozwiązania",
  "Język C++",
  "Język C++, ćwiczenia i rozwiązania",
  "Model obiektu w C++",
  "Programowanie w środowisku system UNIX",
  "Programowanie w systemie UNIX",
  "Wprowadzenie do algorytów",
  "Sztuka programowania tom 1, zeszyt 1",
  "Sztuka programowania tom 1",
  "Sztuka programowania tom 2",
  "Sztuka programowania tom 3",
  "Sztuka programowania tom 4, zeszyt 1",
  "Sztuka programowania tom 4, zeszyt 2",
  "Struktura i interpretacja programów komputerowych",
  "Rzecz o istocie informatyki",
  "Algorytmy aproksymacyjne",
  "Algorytmy genetyczne i ich zastosowania",
  "Algorytmy + struktury danych = programy",
  "Kombinatoryka dla programistów",
  "Logika matematyczna w informatyce",
  "Elementy grafiki komputerowej",
  "Złożoność obliczeniowa",
  "Podstawy oprogramowania",
  "Perełki oprogramowania",
  "Więcej perełek oprogramowania",
  "Systemy rozproszone",
  "Kompilatory, Klasyka Informatyki",
  "Wprowadzenie do systemów baz danych",
  "Podstawowy wykład z systemów baz danych",
  "System baz danych",
  "Implementacja systemów baz danych",
  "Inżynieria oprogramowania",
  "TEX. Przewodnik użytkownika",
  "Wprowadzenie do grafiki komputerowej",
  "Jak to rozwiązać, czyli nowoczesna heurystyka",
  "Algorytmy i struktury danych",
  "Podstawy systemów operacyjnych, tom 1",
  "Podstawy systemów operacyjnych, tom 2",
  "Kompilatory, PWN",
  "Matematyka dyskretna",
  "Matematyka konkretna",
  "Guide to Teaching Puzzle-based Learning",
  "Exploration sin Monte Carlo Methods",
  "Linear Algebra Done Right",
  "Understanding Analysis",
  "Beginning in Algebraic Geometry",
  "Geometric Methods and Applications",
  "Geometry, Audin",
  "The Algorithm Design Manual",
  "Tablice Matematyczne",
  "Geometry, Brannan, Esplen, Gray",
  "Winning Ways for Your Mathematical Plays vol. 1",
  "Winning Ways for Your Mathematical Plays vol. 2",
  "Winning Ways for Your Mathematical Plays vol. 3",
  "Winning Ways for Your Mathematical Plays vol. 4",
  "O kwantach i smokach, Fizyka według Delty",
  "O życiu na żywo. Biologia według Delty",
  "O twierdzeniach i hipotezach. Matematyka według Delty",
  "Codebreaking, a Practical Guide",
]

const rand = (array) => {
  const i = Math.floor(Math.random() * array.length);
  return array[i];
};

console.log(rand(books))
